---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/zacharvey.dev/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
 #   - /bin/cp *.js $DEPLOYPATH